/********************************************************************************
** Form generated from reading UI file 'booking.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_BOOKING_H
#define UI_BOOKING_H

#include <QtCore/QDate>
#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCalendarWidget>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Booking
{
public:
    QWidget *centralwidget;
    QLabel *userLabel;
    QPushButton *btn_logout;
    QLabel *currentuser_lbl;
    QLabel *copyright;
    QLabel *db_lbl;
    QPushButton *btn_return;
    QFrame *frameuser;
    QGroupBox *groupBox;
    QGroupBox *time1hourbox;
    QFrame *line_32;
    QFrame *line_33;
    QFrame *line_34;
    QFrame *line_35;
    QFrame *line_36;
    QFrame *line_37;
    QFrame *line_38;
    QFrame *line_39;
    QPushButton *btn_8am;
    QPushButton *btn_9am;
    QPushButton *btn_10am;
    QPushButton *btn_11am;
    QPushButton *btn_12pm;
    QPushButton *btn_1pm;
    QPushButton *btn_2pm;
    QPushButton *btn_3pm;
    QPushButton *btn_4pm;
    QPushButton *btn_5pm;
    QPushButton *btn_6pm;
    QPushButton *btn_7pm;
    QPushButton *btn_8pm;
    QPushButton *btn_9pm;
    QFrame *line_46;
    QFrame *line_40;
    QPushButton *btn_wholeday;
    QFrame *line_42;
    QCalendarWidget *calendarWidget;
    QFrame *line_41;
    QGroupBox *time2hourbox;
    QFrame *line_44;
    QFrame *line_45;
    QFrame *line_48;
    QFrame *line_50;
    QPushButton *btn_8am_2;
    QPushButton *btn_10am_2;
    QPushButton *btn_12pm_2;
    QPushButton *btn_2pm_2;
    QPushButton *btn_4pm_2;
    QPushButton *btn_6pm_2;
    QPushButton *btn_8pm_2;
    QFrame *line_52;
    QFrame *line_53;
    QPushButton *btn_wholeday_2;
    QFrame *line_54;
    QGroupBox *time3hourbox;
    QFrame *line_47;
    QFrame *line_49;
    QFrame *line_55;
    QPushButton *btn_8am_3;
    QPushButton *btn_11am_3;
    QPushButton *btn_2pm_3;
    QPushButton *btn_5pm_3;
    QPushButton *btn_8pm_3;
    QFrame *line_57;
    QPushButton *btn_wholeday_3;
    QFrame *line_56;
    QGroupBox *time4hourbox;
    QFrame *line_51;
    QFrame *line_58;
    QPushButton *btn_8am_4;
    QPushButton *btn_12pm_4;
    QPushButton *btn_4pm_4;
    QFrame *line_60;
    QPushButton *btn_wholeday_4;
    QFrame *line_61;
    QGroupBox *timecustomize;
    QFrame *line_59;
    QFrame *line_65;
    QLabel *label;
    QComboBox *timefromcmbbox;
    QComboBox *timetocmbbox;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_39;
    QDateEdit *dateEditfrom;
    QLabel *label_40;
    QDateEdit *dateEditto;
    QLabel *label_41;
    QComboBox *daycmbbox;
    QPushButton *btn_customconfirm;
    QPushButton *btn_customreset;
    QPushButton *pushbtn_;
    QGroupBox *confirmation;
    QLabel *facselected_lbl;
    QLabel *maxfac_lbl;
    QPushButton *btn_confirm;
    QLabel *selecteddis_lbl_2;
    QLabel *selecteddis_lbl_3;
    QLabel *selecteddis_lbl;
    QSpinBox *spinBox;
    QPushButton *btn_reset;
    QLabel *dateselectLabel;
    QLabel *timeselectedLabel;
    QLabel *dateselectedLabel;
    QLabel *timeselectLabel;
    QPushButton *btn_reset_2;
    QPushButton *btn_reset_3;
    QLabel *dayselectLabel;
    QLabel *dayselectedLabel;
    QTabWidget *tabWidget;
    QWidget *tab_venue;
    QPushButton *btn_artroom;
    QLabel *fac0004_lbl;
    QLabel *fac0013_lbl;
    QLabel *fac0005_lbl;
    QLabel *fac0021_lbl;
    QPushButton *btn_audioroom;
    QLabel *fac0015_lbl;
    QLabel *fac0018_lbl;
    QLabel *fac0014_lbl;
    QLabel *label_25;
    QLabel *label_11;
    QPushButton *btn_lecturehall;
    QLabel *fac0016_lbl;
    QLabel *fac0001_lbl;
    QPushButton *btn_videoeditroom;
    QLabel *fac0009_lbl;
    QLabel *label_24;
    QLabel *fac0012_lbl;
    QLabel *label_5;
    QLabel *fac0011_lbl;
    QPushButton *btn_volleycourt;
    QLabel *label_21;
    QPushButton *btn_pclab;
    QLabel *label_26;
    QLabel *fac0010_lbl;
    QLabel *label_12;
    QLabel *fac0019_lbl;
    QLabel *fac0002_lbl;
    QPushButton *btn_field;
    QPushButton *btn_pool;
    QPushButton *btn_oslab;
    QPushButton *btn_plaza;
    QLabel *label_27;
    QLabel *label_15;
    QPushButton *btn_skatepark;
    QPushButton *btn_tenniscourt;
    QPushButton *btn_lectureroom;
    QPushButton *btn_gym;
    QLabel *label_20;
    QLabel *fac0007_lbl;
    QLabel *label_8;
    QLabel *fac0006_lbl;
    QPushButton *btn_greensroom;
    QLabel *fac0008_lbl;
    QLabel *label_14;
    QPushButton *btn_tutorialroom;
    QPushButton *btn_eventhall;
    QPushButton *btn_basketballcourt;
    QLabel *label_22;
    QLabel *label_13;
    QLabel *label_17;
    QLabel *label_16;
    QLabel *fac0003_lbl;
    QPushButton *btn_explab;
    QPushButton *btn_engineerlab;
    QLabel *label_7;
    QLabel *fac0000_lbl;
    QPushButton *btn_badmintoncourt;
    QLabel *label_10;
    QLabel *fac0022_lbl;
    QLabel *label_4;
    QLabel *label_19;
    QPushButton *btn_meetingroom;
    QLabel *label_9;
    QPushButton *btn_vidshootroom;
    QLabel *fac0017_lbl;
    QPushButton *btn_corridor;
    QLabel *fac0020_lbl;
    QLabel *label_6;
    QLabel *fac0023_lbl;
    QLabel *label_18;
    QLabel *label_23;
    QWidget *tab_fac;
    QLabel *label_30;
    QLabel *fac0025_lbl;
    QLabel *fac0030_lbl;
    QPushButton *btn_bannerstand;
    QLabel *label_33;
    QPushButton *btn_waterwiper;
    QLabel *fac0029_lbl;
    QPushButton *btn_chair;
    QPushButton *btn_ladder;
    QLabel *fac0027_lbl;
    QLabel *label_28;
    QLabel *fac0024_lbl;
    QPushButton *btn_waterbucket;
    QLabel *label_29;
    QLabel *fac0026_lbl;
    QLabel *label_36;
    QPushButton *btn_broom;
    QLabel *fac0028_lbl;
    QLabel *label_37;
    QLabel *fac0033_lbl;
    QLabel *label_38;
    QLabel *fac0031_lbl;
    QPushButton *btn_waterpipe;
    QLabel *fac0032_lbl;
    QLabel *fac0034_lbl;
    QLabel *label_34;
    QPushButton *btn_queuebarrier;
    QLabel *label_35;
    QLabel *label_32;
    QPushButton *btn_mop;
    QPushButton *btn_table;
    QPushButton *btn_bucket;
    QLabel *label_31;
    QLabel *datedisplay;
    QComboBox *timecmbBox;
    QFrame *line_2;
    QFrame *oframe1;
    QFrame *oframe4;
    QFrame *oframe3;
    QFrame *oframe2;
    QFrame *frameadmin;
    QLabel *datedisplay_2;
    QLabel *datedisplaylbl2;
    QTableView *table_availability;
    QFrame *frameadmin2;
    QTableView *table_bookings;
    QLabel *datedisplaylbl2_2;
    QLabel *datedisplay_3;
    QLabel *timecurrentLabel;
    QLabel *timedisplay;

    void setupUi(QMainWindow *Booking)
    {
        if (Booking->objectName().isEmpty())
            Booking->setObjectName(QString::fromUtf8("Booking"));
        Booking->resize(800, 600);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        Booking->setWindowIcon(icon);
        centralwidget = new QWidget(Booking);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        userLabel = new QLabel(centralwidget);
        userLabel->setObjectName(QString::fromUtf8("userLabel"));
        userLabel->setGeometry(QRect(16, 10, 81, 16));
        btn_logout = new QPushButton(centralwidget);
        btn_logout->setObjectName(QString::fromUtf8("btn_logout"));
        btn_logout->setGeometry(QRect(710, 10, 75, 23));
        btn_logout->setAutoDefault(false);
        btn_logout->setFlat(false);
        currentuser_lbl = new QLabel(centralwidget);
        currentuser_lbl->setObjectName(QString::fromUtf8("currentuser_lbl"));
        currentuser_lbl->setGeometry(QRect(100, 10, 81, 16));
        copyright = new QLabel(centralwidget);
        copyright->setObjectName(QString::fromUtf8("copyright"));
        copyright->setGeometry(QRect(12, 570, 111, 16));
        db_lbl = new QLabel(centralwidget);
        db_lbl->setObjectName(QString::fromUtf8("db_lbl"));
        db_lbl->setGeometry(QRect(16, 22, 211, 16));
        btn_return = new QPushButton(centralwidget);
        btn_return->setObjectName(QString::fromUtf8("btn_return"));
        btn_return->setGeometry(QRect(630, 10, 75, 23));
        btn_return->setAutoDefault(false);
        btn_return->setFlat(false);
        frameuser = new QFrame(centralwidget);
        frameuser->setObjectName(QString::fromUtf8("frameuser"));
        frameuser->setGeometry(QRect(5, 45, 781, 581));
        frameuser->setFrameShape(QFrame::StyledPanel);
        frameuser->setFrameShadow(QFrame::Raised);
        groupBox = new QGroupBox(frameuser);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(2, 18, 381, 441));
        time1hourbox = new QGroupBox(groupBox);
        time1hourbox->setObjectName(QString::fromUtf8("time1hourbox"));
        time1hourbox->setGeometry(QRect(10, 240, 361, 211));
        line_32 = new QFrame(time1hourbox);
        line_32->setObjectName(QString::fromUtf8("line_32"));
        line_32->setGeometry(QRect(0, 51, 381, 20));
        line_32->setFrameShape(QFrame::HLine);
        line_32->setFrameShadow(QFrame::Sunken);
        line_33 = new QFrame(time1hourbox);
        line_33->setObjectName(QString::fromUtf8("line_33"));
        line_33->setGeometry(QRect(0, 31, 381, 20));
        line_33->setFrameShape(QFrame::HLine);
        line_33->setFrameShadow(QFrame::Sunken);
        line_34 = new QFrame(time1hourbox);
        line_34->setObjectName(QString::fromUtf8("line_34"));
        line_34->setGeometry(QRect(0, 71, 381, 20));
        line_34->setFrameShape(QFrame::HLine);
        line_34->setFrameShadow(QFrame::Sunken);
        line_35 = new QFrame(time1hourbox);
        line_35->setObjectName(QString::fromUtf8("line_35"));
        line_35->setGeometry(QRect(0, 91, 381, 20));
        line_35->setFrameShape(QFrame::HLine);
        line_35->setFrameShadow(QFrame::Sunken);
        line_36 = new QFrame(time1hourbox);
        line_36->setObjectName(QString::fromUtf8("line_36"));
        line_36->setGeometry(QRect(0, 111, 381, 20));
        line_36->setFrameShape(QFrame::HLine);
        line_36->setFrameShadow(QFrame::Sunken);
        line_37 = new QFrame(time1hourbox);
        line_37->setObjectName(QString::fromUtf8("line_37"));
        line_37->setGeometry(QRect(0, 131, 381, 20));
        line_37->setFrameShape(QFrame::HLine);
        line_37->setFrameShadow(QFrame::Sunken);
        line_38 = new QFrame(time1hourbox);
        line_38->setObjectName(QString::fromUtf8("line_38"));
        line_38->setGeometry(QRect(0, 151, 381, 20));
        line_38->setFrameShape(QFrame::HLine);
        line_38->setFrameShadow(QFrame::Sunken);
        line_39 = new QFrame(time1hourbox);
        line_39->setObjectName(QString::fromUtf8("line_39"));
        line_39->setGeometry(QRect(0, 171, 381, 20));
        line_39->setFrameShape(QFrame::HLine);
        line_39->setFrameShadow(QFrame::Sunken);
        btn_8am = new QPushButton(time1hourbox);
        btn_8am->setObjectName(QString::fromUtf8("btn_8am"));
        btn_8am->setGeometry(QRect(0, 41, 191, 21));
        btn_8am->setStyleSheet(QString::fromUtf8(""));
        btn_8am->setAutoDefault(false);
        btn_8am->setFlat(true);
        btn_9am = new QPushButton(time1hourbox);
        btn_9am->setObjectName(QString::fromUtf8("btn_9am"));
        btn_9am->setGeometry(QRect(0, 61, 191, 21));
        btn_9am->setFlat(true);
        btn_10am = new QPushButton(time1hourbox);
        btn_10am->setObjectName(QString::fromUtf8("btn_10am"));
        btn_10am->setGeometry(QRect(0, 79, 191, 21));
        btn_10am->setFlat(true);
        btn_11am = new QPushButton(time1hourbox);
        btn_11am->setObjectName(QString::fromUtf8("btn_11am"));
        btn_11am->setGeometry(QRect(0, 101, 191, 21));
        btn_11am->setFlat(true);
        btn_12pm = new QPushButton(time1hourbox);
        btn_12pm->setObjectName(QString::fromUtf8("btn_12pm"));
        btn_12pm->setGeometry(QRect(0, 120, 191, 21));
        btn_12pm->setFlat(true);
        btn_1pm = new QPushButton(time1hourbox);
        btn_1pm->setObjectName(QString::fromUtf8("btn_1pm"));
        btn_1pm->setGeometry(QRect(0, 141, 191, 21));
        btn_1pm->setFlat(true);
        btn_2pm = new QPushButton(time1hourbox);
        btn_2pm->setObjectName(QString::fromUtf8("btn_2pm"));
        btn_2pm->setGeometry(QRect(0, 161, 191, 21));
        btn_2pm->setFlat(true);
        btn_3pm = new QPushButton(time1hourbox);
        btn_3pm->setObjectName(QString::fromUtf8("btn_3pm"));
        btn_3pm->setGeometry(QRect(190, 41, 171, 21));
        btn_3pm->setFlat(true);
        btn_4pm = new QPushButton(time1hourbox);
        btn_4pm->setObjectName(QString::fromUtf8("btn_4pm"));
        btn_4pm->setGeometry(QRect(190, 61, 171, 21));
        btn_4pm->setFlat(true);
        btn_5pm = new QPushButton(time1hourbox);
        btn_5pm->setObjectName(QString::fromUtf8("btn_5pm"));
        btn_5pm->setGeometry(QRect(190, 79, 171, 21));
        btn_5pm->setFlat(true);
        btn_6pm = new QPushButton(time1hourbox);
        btn_6pm->setObjectName(QString::fromUtf8("btn_6pm"));
        btn_6pm->setGeometry(QRect(190, 101, 171, 21));
        btn_6pm->setFlat(true);
        btn_7pm = new QPushButton(time1hourbox);
        btn_7pm->setObjectName(QString::fromUtf8("btn_7pm"));
        btn_7pm->setGeometry(QRect(190, 120, 171, 21));
        btn_7pm->setFlat(true);
        btn_8pm = new QPushButton(time1hourbox);
        btn_8pm->setObjectName(QString::fromUtf8("btn_8pm"));
        btn_8pm->setGeometry(QRect(190, 141, 171, 21));
        btn_8pm->setFlat(true);
        btn_9pm = new QPushButton(time1hourbox);
        btn_9pm->setObjectName(QString::fromUtf8("btn_9pm"));
        btn_9pm->setGeometry(QRect(190, 161, 171, 21));
        btn_9pm->setFlat(true);
        line_46 = new QFrame(time1hourbox);
        line_46->setObjectName(QString::fromUtf8("line_46"));
        line_46->setGeometry(QRect(0, 311, 161, 16));
        line_46->setFrameShape(QFrame::HLine);
        line_46->setFrameShadow(QFrame::Sunken);
        line_40 = new QFrame(time1hourbox);
        line_40->setObjectName(QString::fromUtf8("line_40"));
        line_40->setGeometry(QRect(180, 41, 20, 141));
        line_40->setFrameShape(QFrame::VLine);
        line_40->setFrameShadow(QFrame::Sunken);
        btn_wholeday = new QPushButton(time1hourbox);
        btn_wholeday->setObjectName(QString::fromUtf8("btn_wholeday"));
        btn_wholeday->setGeometry(QRect(0, 179, 361, 21));
        btn_wholeday->setFlat(true);
        line_42 = new QFrame(time1hourbox);
        line_42->setObjectName(QString::fromUtf8("line_42"));
        line_42->setGeometry(QRect(0, 191, 381, 20));
        line_42->setFrameShape(QFrame::HLine);
        line_42->setFrameShadow(QFrame::Sunken);
        line_33->raise();
        line_32->raise();
        line_34->raise();
        line_37->raise();
        btn_8am->raise();
        btn_9am->raise();
        btn_10am->raise();
        btn_12pm->raise();
        btn_1pm->raise();
        line_35->raise();
        line_36->raise();
        line_38->raise();
        line_39->raise();
        btn_11am->raise();
        btn_2pm->raise();
        btn_3pm->raise();
        btn_4pm->raise();
        btn_5pm->raise();
        btn_6pm->raise();
        btn_7pm->raise();
        btn_8pm->raise();
        btn_9pm->raise();
        line_46->raise();
        line_40->raise();
        btn_wholeday->raise();
        line_42->raise();
        calendarWidget = new QCalendarWidget(groupBox);
        calendarWidget->setObjectName(QString::fromUtf8("calendarWidget"));
        calendarWidget->setEnabled(true);
        calendarWidget->setGeometry(QRect(10, 10, 361, 231));
        QFont font;
        font.setBold(false);
        font.setItalic(false);
        font.setUnderline(false);
        font.setWeight(50);
        calendarWidget->setFont(font);
        calendarWidget->setCursor(QCursor(Qt::PointingHandCursor));
        calendarWidget->setAcceptDrops(false);
        calendarWidget->setAutoFillBackground(true);
        calendarWidget->setStyleSheet(QString::fromUtf8("selection-background-color: qlineargradient(spread:pad, x1:0.624591, y1:0.647, x2:0, y2:0, stop:0 rgba(31, 180, 214, 255), stop:1 rgba(183, 183, 183, 255));\n"
"\n"
"\n"
""));
        calendarWidget->setSelectedDate(QDate(2019, 8, 21));
        calendarWidget->setMinimumDate(QDate(2019, 1, 1));
        calendarWidget->setGridVisible(true);
        calendarWidget->setHorizontalHeaderFormat(QCalendarWidget::ShortDayNames);
        calendarWidget->setVerticalHeaderFormat(QCalendarWidget::NoVerticalHeader);
        calendarWidget->setNavigationBarVisible(true);
        calendarWidget->setDateEditEnabled(true);
        line_41 = new QFrame(groupBox);
        line_41->setObjectName(QString::fromUtf8("line_41"));
        line_41->setGeometry(QRect(370, 450, 20, 81));
        line_41->setFrameShape(QFrame::VLine);
        line_41->setFrameShadow(QFrame::Sunken);
        time2hourbox = new QGroupBox(groupBox);
        time2hourbox->setObjectName(QString::fromUtf8("time2hourbox"));
        time2hourbox->setGeometry(QRect(10, 240, 361, 211));
        line_44 = new QFrame(time2hourbox);
        line_44->setObjectName(QString::fromUtf8("line_44"));
        line_44->setGeometry(QRect(0, 31, 381, 20));
        line_44->setFrameShape(QFrame::HLine);
        line_44->setFrameShadow(QFrame::Sunken);
        line_45 = new QFrame(time2hourbox);
        line_45->setObjectName(QString::fromUtf8("line_45"));
        line_45->setGeometry(QRect(0, 71, 381, 20));
        line_45->setFrameShape(QFrame::HLine);
        line_45->setFrameShadow(QFrame::Sunken);
        line_48 = new QFrame(time2hourbox);
        line_48->setObjectName(QString::fromUtf8("line_48"));
        line_48->setGeometry(QRect(0, 111, 381, 20));
        line_48->setFrameShape(QFrame::HLine);
        line_48->setFrameShadow(QFrame::Sunken);
        line_50 = new QFrame(time2hourbox);
        line_50->setObjectName(QString::fromUtf8("line_50"));
        line_50->setGeometry(QRect(0, 151, 381, 20));
        line_50->setFrameShape(QFrame::HLine);
        line_50->setFrameShadow(QFrame::Sunken);
        btn_8am_2 = new QPushButton(time2hourbox);
        btn_8am_2->setObjectName(QString::fromUtf8("btn_8am_2"));
        btn_8am_2->setGeometry(QRect(0, 41, 191, 41));
        btn_8am_2->setStyleSheet(QString::fromUtf8(""));
        btn_8am_2->setAutoDefault(false);
        btn_8am_2->setFlat(true);
        btn_10am_2 = new QPushButton(time2hourbox);
        btn_10am_2->setObjectName(QString::fromUtf8("btn_10am_2"));
        btn_10am_2->setGeometry(QRect(0, 79, 191, 41));
        btn_10am_2->setFlat(true);
        btn_12pm_2 = new QPushButton(time2hourbox);
        btn_12pm_2->setObjectName(QString::fromUtf8("btn_12pm_2"));
        btn_12pm_2->setGeometry(QRect(0, 120, 191, 41));
        btn_12pm_2->setFlat(true);
        btn_2pm_2 = new QPushButton(time2hourbox);
        btn_2pm_2->setObjectName(QString::fromUtf8("btn_2pm_2"));
        btn_2pm_2->setGeometry(QRect(0, 160, 191, 41));
        btn_2pm_2->setFlat(true);
        btn_4pm_2 = new QPushButton(time2hourbox);
        btn_4pm_2->setObjectName(QString::fromUtf8("btn_4pm_2"));
        btn_4pm_2->setGeometry(QRect(190, 40, 171, 41));
        btn_4pm_2->setFlat(true);
        btn_6pm_2 = new QPushButton(time2hourbox);
        btn_6pm_2->setObjectName(QString::fromUtf8("btn_6pm_2"));
        btn_6pm_2->setGeometry(QRect(190, 80, 171, 41));
        btn_6pm_2->setFlat(true);
        btn_8pm_2 = new QPushButton(time2hourbox);
        btn_8pm_2->setObjectName(QString::fromUtf8("btn_8pm_2"));
        btn_8pm_2->setGeometry(QRect(190, 120, 171, 41));
        btn_8pm_2->setFlat(true);
        line_52 = new QFrame(time2hourbox);
        line_52->setObjectName(QString::fromUtf8("line_52"));
        line_52->setGeometry(QRect(0, 311, 161, 16));
        line_52->setFrameShape(QFrame::HLine);
        line_52->setFrameShadow(QFrame::Sunken);
        line_53 = new QFrame(time2hourbox);
        line_53->setObjectName(QString::fromUtf8("line_53"));
        line_53->setGeometry(QRect(180, 41, 20, 161));
        line_53->setFrameShape(QFrame::VLine);
        line_53->setFrameShadow(QFrame::Sunken);
        btn_wholeday_2 = new QPushButton(time2hourbox);
        btn_wholeday_2->setObjectName(QString::fromUtf8("btn_wholeday_2"));
        btn_wholeday_2->setGeometry(QRect(190, 160, 171, 41));
        btn_wholeday_2->setFlat(true);
        line_54 = new QFrame(time2hourbox);
        line_54->setObjectName(QString::fromUtf8("line_54"));
        line_54->setGeometry(QRect(0, 191, 381, 20));
        line_54->setFrameShape(QFrame::HLine);
        line_54->setFrameShadow(QFrame::Sunken);
        time3hourbox = new QGroupBox(groupBox);
        time3hourbox->setObjectName(QString::fromUtf8("time3hourbox"));
        time3hourbox->setGeometry(QRect(10, 240, 361, 211));
        line_47 = new QFrame(time3hourbox);
        line_47->setObjectName(QString::fromUtf8("line_47"));
        line_47->setGeometry(QRect(0, 31, 381, 20));
        line_47->setFrameShape(QFrame::HLine);
        line_47->setFrameShadow(QFrame::Sunken);
        line_49 = new QFrame(time3hourbox);
        line_49->setObjectName(QString::fromUtf8("line_49"));
        line_49->setGeometry(QRect(0, 81, 381, 20));
        line_49->setFrameShape(QFrame::HLine);
        line_49->setFrameShadow(QFrame::Sunken);
        line_55 = new QFrame(time3hourbox);
        line_55->setObjectName(QString::fromUtf8("line_55"));
        line_55->setGeometry(QRect(0, 130, 361, 20));
        line_55->setFrameShape(QFrame::HLine);
        line_55->setFrameShadow(QFrame::Sunken);
        btn_8am_3 = new QPushButton(time3hourbox);
        btn_8am_3->setObjectName(QString::fromUtf8("btn_8am_3"));
        btn_8am_3->setGeometry(QRect(0, 40, 191, 51));
        btn_8am_3->setStyleSheet(QString::fromUtf8(""));
        btn_8am_3->setAutoDefault(false);
        btn_8am_3->setFlat(true);
        btn_11am_3 = new QPushButton(time3hourbox);
        btn_11am_3->setObjectName(QString::fromUtf8("btn_11am_3"));
        btn_11am_3->setGeometry(QRect(0, 90, 191, 51));
        btn_11am_3->setFlat(true);
        btn_2pm_3 = new QPushButton(time3hourbox);
        btn_2pm_3->setObjectName(QString::fromUtf8("btn_2pm_3"));
        btn_2pm_3->setGeometry(QRect(0, 140, 191, 61));
        btn_2pm_3->setFlat(true);
        btn_5pm_3 = new QPushButton(time3hourbox);
        btn_5pm_3->setObjectName(QString::fromUtf8("btn_5pm_3"));
        btn_5pm_3->setGeometry(QRect(190, 40, 171, 51));
        btn_5pm_3->setFlat(true);
        btn_8pm_3 = new QPushButton(time3hourbox);
        btn_8pm_3->setObjectName(QString::fromUtf8("btn_8pm_3"));
        btn_8pm_3->setGeometry(QRect(190, 90, 171, 51));
        btn_8pm_3->setFlat(true);
        line_57 = new QFrame(time3hourbox);
        line_57->setObjectName(QString::fromUtf8("line_57"));
        line_57->setGeometry(QRect(180, 41, 20, 161));
        line_57->setFrameShape(QFrame::VLine);
        line_57->setFrameShadow(QFrame::Sunken);
        btn_wholeday_3 = new QPushButton(time3hourbox);
        btn_wholeday_3->setObjectName(QString::fromUtf8("btn_wholeday_3"));
        btn_wholeday_3->setGeometry(QRect(190, 140, 171, 61));
        btn_wholeday_3->setFlat(true);
        line_56 = new QFrame(time3hourbox);
        line_56->setObjectName(QString::fromUtf8("line_56"));
        line_56->setGeometry(QRect(0, 190, 361, 20));
        line_56->setFrameShape(QFrame::HLine);
        line_56->setFrameShadow(QFrame::Sunken);
        time4hourbox = new QGroupBox(groupBox);
        time4hourbox->setObjectName(QString::fromUtf8("time4hourbox"));
        time4hourbox->setGeometry(QRect(10, 240, 361, 211));
        line_51 = new QFrame(time4hourbox);
        line_51->setObjectName(QString::fromUtf8("line_51"));
        line_51->setGeometry(QRect(0, 31, 381, 20));
        line_51->setFrameShape(QFrame::HLine);
        line_51->setFrameShadow(QFrame::Sunken);
        line_58 = new QFrame(time4hourbox);
        line_58->setObjectName(QString::fromUtf8("line_58"));
        line_58->setGeometry(QRect(0, 110, 381, 20));
        line_58->setFrameShape(QFrame::HLine);
        line_58->setFrameShadow(QFrame::Sunken);
        btn_8am_4 = new QPushButton(time4hourbox);
        btn_8am_4->setObjectName(QString::fromUtf8("btn_8am_4"));
        btn_8am_4->setGeometry(QRect(0, 40, 191, 81));
        btn_8am_4->setStyleSheet(QString::fromUtf8(""));
        btn_8am_4->setAutoDefault(false);
        btn_8am_4->setFlat(true);
        btn_12pm_4 = new QPushButton(time4hourbox);
        btn_12pm_4->setObjectName(QString::fromUtf8("btn_12pm_4"));
        btn_12pm_4->setGeometry(QRect(0, 120, 191, 81));
        btn_12pm_4->setFlat(true);
        btn_4pm_4 = new QPushButton(time4hourbox);
        btn_4pm_4->setObjectName(QString::fromUtf8("btn_4pm_4"));
        btn_4pm_4->setGeometry(QRect(190, 40, 171, 81));
        btn_4pm_4->setFlat(true);
        line_60 = new QFrame(time4hourbox);
        line_60->setObjectName(QString::fromUtf8("line_60"));
        line_60->setGeometry(QRect(180, 41, 20, 161));
        line_60->setFrameShape(QFrame::VLine);
        line_60->setFrameShadow(QFrame::Sunken);
        btn_wholeday_4 = new QPushButton(time4hourbox);
        btn_wholeday_4->setObjectName(QString::fromUtf8("btn_wholeday_4"));
        btn_wholeday_4->setGeometry(QRect(190, 120, 171, 81));
        btn_wholeday_4->setFlat(true);
        line_61 = new QFrame(time4hourbox);
        line_61->setObjectName(QString::fromUtf8("line_61"));
        line_61->setGeometry(QRect(0, 190, 361, 20));
        line_61->setFrameShape(QFrame::HLine);
        line_61->setFrameShadow(QFrame::Sunken);
        timecustomize = new QGroupBox(groupBox);
        timecustomize->setObjectName(QString::fromUtf8("timecustomize"));
        timecustomize->setGeometry(QRect(10, 240, 361, 211));
        line_59 = new QFrame(timecustomize);
        line_59->setObjectName(QString::fromUtf8("line_59"));
        line_59->setGeometry(QRect(0, 31, 381, 20));
        line_59->setFrameShape(QFrame::HLine);
        line_59->setFrameShadow(QFrame::Sunken);
        line_65 = new QFrame(timecustomize);
        line_65->setObjectName(QString::fromUtf8("line_65"));
        line_65->setGeometry(QRect(0, 190, 361, 20));
        line_65->setFrameShape(QFrame::HLine);
        line_65->setFrameShadow(QFrame::Sunken);
        label = new QLabel(timecustomize);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(60, 70, 81, 21));
        timefromcmbbox = new QComboBox(timecustomize);
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->addItem(QString());
        timefromcmbbox->setObjectName(QString::fromUtf8("timefromcmbbox"));
        timefromcmbbox->setGeometry(QRect(140, 70, 51, 22));
        timetocmbbox = new QComboBox(timecustomize);
        timetocmbbox->setObjectName(QString::fromUtf8("timetocmbbox"));
        timetocmbbox->setGeometry(QRect(220, 70, 51, 22));
        label_2 = new QLabel(timecustomize);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(200, 70, 16, 21));
        label_3 = new QLabel(timecustomize);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(60, 100, 81, 21));
        label_39 = new QLabel(timecustomize);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(0, 180, 81, 21));
        dateEditfrom = new QDateEdit(timecustomize);
        dateEditfrom->setObjectName(QString::fromUtf8("dateEditfrom"));
        dateEditfrom->setGeometry(QRect(140, 100, 81, 22));
        dateEditfrom->setCalendarPopup(true);
        label_40 = new QLabel(timecustomize);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(60, 130, 81, 21));
        dateEditto = new QDateEdit(timecustomize);
        dateEditto->setObjectName(QString::fromUtf8("dateEditto"));
        dateEditto->setGeometry(QRect(250, 100, 81, 22));
        dateEditto->setCalendarPopup(true);
        label_41 = new QLabel(timecustomize);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(230, 100, 16, 21));
        daycmbbox = new QComboBox(timecustomize);
        daycmbbox->addItem(QString());
        daycmbbox->addItem(QString());
        daycmbbox->addItem(QString());
        daycmbbox->addItem(QString());
        daycmbbox->addItem(QString());
        daycmbbox->addItem(QString());
        daycmbbox->addItem(QString());
        daycmbbox->addItem(QString());
        daycmbbox->setObjectName(QString::fromUtf8("daycmbbox"));
        daycmbbox->setGeometry(QRect(140, 130, 81, 22));
        btn_customconfirm = new QPushButton(timecustomize);
        btn_customconfirm->setObjectName(QString::fromUtf8("btn_customconfirm"));
        btn_customconfirm->setGeometry(QRect(280, 170, 75, 23));
        btn_customreset = new QPushButton(timecustomize);
        btn_customreset->setObjectName(QString::fromUtf8("btn_customreset"));
        btn_customreset->setGeometry(QRect(200, 170, 75, 23));
        pushbtn_ = new QPushButton(frameuser);
        pushbtn_->setObjectName(QString::fromUtf8("pushbtn_"));
        pushbtn_->setGeometry(QRect(232, 0, 71, 21));
        confirmation = new QGroupBox(frameuser);
        confirmation->setObjectName(QString::fromUtf8("confirmation"));
        confirmation->setGeometry(QRect(5, 468, 781, 80));
        confirmation->setAlignment(Qt::AlignCenter);
        confirmation->setFlat(true);
        facselected_lbl = new QLabel(confirmation);
        facselected_lbl->setObjectName(QString::fromUtf8("facselected_lbl"));
        facselected_lbl->setGeometry(QRect(510, 0, 191, 16));
        maxfac_lbl = new QLabel(confirmation);
        maxfac_lbl->setObjectName(QString::fromUtf8("maxfac_lbl"));
        maxfac_lbl->setGeometry(QRect(510, 15, 41, 16));
        btn_confirm = new QPushButton(confirmation);
        btn_confirm->setObjectName(QString::fromUtf8("btn_confirm"));
        btn_confirm->setGeometry(QRect(690, 50, 75, 23));
        btn_confirm->setAutoDefault(false);
        btn_confirm->setFlat(false);
        selecteddis_lbl_2 = new QLabel(confirmation);
        selecteddis_lbl_2->setObjectName(QString::fromUtf8("selecteddis_lbl_2"));
        selecteddis_lbl_2->setGeometry(QRect(386, 15, 121, 16));
        selecteddis_lbl_3 = new QLabel(confirmation);
        selecteddis_lbl_3->setObjectName(QString::fromUtf8("selecteddis_lbl_3"));
        selecteddis_lbl_3->setGeometry(QRect(386, 30, 171, 16));
        selecteddis_lbl = new QLabel(confirmation);
        selecteddis_lbl->setObjectName(QString::fromUtf8("selecteddis_lbl"));
        selecteddis_lbl->setGeometry(QRect(386, 0, 131, 16));
        spinBox = new QSpinBox(confirmation);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(510, 30, 42, 16));
        btn_reset = new QPushButton(confirmation);
        btn_reset->setObjectName(QString::fromUtf8("btn_reset"));
        btn_reset->setGeometry(QRect(610, 50, 75, 23));
        btn_reset->setAutoDefault(false);
        btn_reset->setFlat(false);
        dateselectLabel = new QLabel(confirmation);
        dateselectLabel->setObjectName(QString::fromUtf8("dateselectLabel"));
        dateselectLabel->setGeometry(QRect(8, 0, 71, 16));
        timeselectedLabel = new QLabel(confirmation);
        timeselectedLabel->setObjectName(QString::fromUtf8("timeselectedLabel"));
        timeselectedLabel->setGeometry(QRect(80, 13, 91, 20));
        dateselectedLabel = new QLabel(confirmation);
        dateselectedLabel->setObjectName(QString::fromUtf8("dateselectedLabel"));
        dateselectedLabel->setGeometry(QRect(80, -2, 251, 20));
        timeselectLabel = new QLabel(confirmation);
        timeselectLabel->setObjectName(QString::fromUtf8("timeselectLabel"));
        timeselectLabel->setGeometry(QRect(8, 15, 71, 16));
        btn_reset_2 = new QPushButton(confirmation);
        btn_reset_2->setObjectName(QString::fromUtf8("btn_reset_2"));
        btn_reset_2->setGeometry(QRect(368, 50, 111, 23));
        btn_reset_2->setAutoDefault(false);
        btn_reset_2->setFlat(false);
        btn_reset_3 = new QPushButton(confirmation);
        btn_reset_3->setObjectName(QString::fromUtf8("btn_reset_3"));
        btn_reset_3->setGeometry(QRect(484, 50, 121, 23));
        btn_reset_3->setAutoDefault(false);
        btn_reset_3->setFlat(false);
        dayselectLabel = new QLabel(confirmation);
        dayselectLabel->setObjectName(QString::fromUtf8("dayselectLabel"));
        dayselectLabel->setGeometry(QRect(8, 30, 71, 16));
        dayselectedLabel = new QLabel(confirmation);
        dayselectedLabel->setObjectName(QString::fromUtf8("dayselectedLabel"));
        dayselectedLabel->setGeometry(QRect(82, 30, 71, 16));
        tabWidget = new QTabWidget(frameuser);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(392, 18, 391, 441));
        tabWidget->setCursor(QCursor(Qt::PointingHandCursor));
        tab_venue = new QWidget();
        tab_venue->setObjectName(QString::fromUtf8("tab_venue"));
        btn_artroom = new QPushButton(tab_venue);
        btn_artroom->setObjectName(QString::fromUtf8("btn_artroom"));
        btn_artroom->setGeometry(QRect(1, 122, 91, 41));
        btn_artroom->setCursor(QCursor(Qt::PointingHandCursor));
        fac0004_lbl = new QLabel(tab_venue);
        fac0004_lbl->setObjectName(QString::fromUtf8("fac0004_lbl"));
        fac0004_lbl->setGeometry(QRect(53, 100, 41, 16));
        fac0013_lbl = new QLabel(tab_venue);
        fac0013_lbl->setObjectName(QString::fromUtf8("fac0013_lbl"));
        fac0013_lbl->setGeometry(QRect(150, 220, 41, 16));
        fac0005_lbl = new QLabel(tab_venue);
        fac0005_lbl->setObjectName(QString::fromUtf8("fac0005_lbl"));
        fac0005_lbl->setGeometry(QRect(150, 100, 41, 16));
        fac0021_lbl = new QLabel(tab_venue);
        fac0021_lbl->setObjectName(QString::fromUtf8("fac0021_lbl"));
        fac0021_lbl->setGeometry(QRect(150, 340, 41, 16));
        btn_audioroom = new QPushButton(tab_venue);
        btn_audioroom->setObjectName(QString::fromUtf8("btn_audioroom"));
        btn_audioroom->setGeometry(QRect(294, 122, 91, 41));
        btn_audioroom->setCursor(QCursor(Qt::PointingHandCursor));
        fac0015_lbl = new QLabel(tab_venue);
        fac0015_lbl->setObjectName(QString::fromUtf8("fac0015_lbl"));
        fac0015_lbl->setGeometry(QRect(346, 220, 41, 16));
        fac0018_lbl = new QLabel(tab_venue);
        fac0018_lbl->setObjectName(QString::fromUtf8("fac0018_lbl"));
        fac0018_lbl->setGeometry(QRect(248, 280, 41, 16));
        fac0014_lbl = new QLabel(tab_venue);
        fac0014_lbl->setObjectName(QString::fromUtf8("fac0014_lbl"));
        fac0014_lbl->setGeometry(QRect(248, 220, 41, 16));
        label_25 = new QLabel(tab_venue);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(294, 342, 47, 13));
        label_11 = new QLabel(tab_venue);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(296, 102, 47, 13));
        btn_lecturehall = new QPushButton(tab_venue);
        btn_lecturehall->setObjectName(QString::fromUtf8("btn_lecturehall"));
        btn_lecturehall->setGeometry(QRect(98, 2, 91, 41));
        btn_lecturehall->setCursor(QCursor(Qt::PointingHandCursor));
        fac0016_lbl = new QLabel(tab_venue);
        fac0016_lbl->setObjectName(QString::fromUtf8("fac0016_lbl"));
        fac0016_lbl->setGeometry(QRect(53, 280, 41, 16));
        fac0001_lbl = new QLabel(tab_venue);
        fac0001_lbl->setObjectName(QString::fromUtf8("fac0001_lbl"));
        fac0001_lbl->setGeometry(QRect(150, 40, 41, 16));
        btn_videoeditroom = new QPushButton(tab_venue);
        btn_videoeditroom->setObjectName(QString::fromUtf8("btn_videoeditroom"));
        btn_videoeditroom->setGeometry(QRect(1, 182, 91, 41));
        btn_videoeditroom->setCursor(QCursor(Qt::PointingHandCursor));
        fac0009_lbl = new QLabel(tab_venue);
        fac0009_lbl->setObjectName(QString::fromUtf8("fac0009_lbl"));
        fac0009_lbl->setGeometry(QRect(150, 160, 41, 16));
        label_24 = new QLabel(tab_venue);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(100, 342, 47, 13));
        fac0012_lbl = new QLabel(tab_venue);
        fac0012_lbl->setObjectName(QString::fromUtf8("fac0012_lbl"));
        fac0012_lbl->setGeometry(QRect(53, 220, 41, 16));
        label_5 = new QLabel(tab_venue);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(100, 42, 47, 13));
        fac0011_lbl = new QLabel(tab_venue);
        fac0011_lbl->setObjectName(QString::fromUtf8("fac0011_lbl"));
        fac0011_lbl->setGeometry(QRect(346, 160, 41, 16));
        btn_volleycourt = new QPushButton(tab_venue);
        btn_volleycourt->setObjectName(QString::fromUtf8("btn_volleycourt"));
        btn_volleycourt->setGeometry(QRect(98, 302, 91, 41));
        btn_volleycourt->setCursor(QCursor(Qt::PointingHandCursor));
        label_21 = new QLabel(tab_venue);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(198, 282, 47, 13));
        btn_pclab = new QPushButton(tab_venue);
        btn_pclab->setObjectName(QString::fromUtf8("btn_pclab"));
        btn_pclab->setGeometry(QRect(1, 62, 91, 41));
        btn_pclab->setCursor(QCursor(Qt::PointingHandCursor));
        label_26 = new QLabel(tab_venue);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(198, 342, 47, 13));
        fac0010_lbl = new QLabel(tab_venue);
        fac0010_lbl->setObjectName(QString::fromUtf8("fac0010_lbl"));
        fac0010_lbl->setGeometry(QRect(248, 160, 41, 16));
        label_12 = new QLabel(tab_venue);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(100, 162, 47, 13));
        fac0019_lbl = new QLabel(tab_venue);
        fac0019_lbl->setObjectName(QString::fromUtf8("fac0019_lbl"));
        fac0019_lbl->setGeometry(QRect(344, 280, 41, 16));
        fac0002_lbl = new QLabel(tab_venue);
        fac0002_lbl->setObjectName(QString::fromUtf8("fac0002_lbl"));
        fac0002_lbl->setGeometry(QRect(248, 40, 41, 16));
        btn_field = new QPushButton(tab_venue);
        btn_field->setObjectName(QString::fromUtf8("btn_field"));
        btn_field->setGeometry(QRect(1, 302, 91, 41));
        btn_field->setCursor(QCursor(Qt::PointingHandCursor));
        btn_pool = new QPushButton(tab_venue);
        btn_pool->setObjectName(QString::fromUtf8("btn_pool"));
        btn_pool->setGeometry(QRect(294, 242, 91, 41));
        btn_pool->setCursor(QCursor(Qt::PointingHandCursor));
        btn_oslab = new QPushButton(tab_venue);
        btn_oslab->setObjectName(QString::fromUtf8("btn_oslab"));
        btn_oslab->setGeometry(QRect(294, 2, 91, 41));
        btn_oslab->setCursor(QCursor(Qt::PointingHandCursor));
        btn_plaza = new QPushButton(tab_venue);
        btn_plaza->setObjectName(QString::fromUtf8("btn_plaza"));
        btn_plaza->setGeometry(QRect(294, 182, 91, 41));
        btn_plaza->setCursor(QCursor(Qt::PointingHandCursor));
        label_27 = new QLabel(tab_venue);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(3, 342, 47, 13));
        label_15 = new QLabel(tab_venue);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(198, 162, 47, 13));
        btn_skatepark = new QPushButton(tab_venue);
        btn_skatepark->setObjectName(QString::fromUtf8("btn_skatepark"));
        btn_skatepark->setGeometry(QRect(294, 302, 91, 41));
        btn_skatepark->setCursor(QCursor(Qt::PointingHandCursor));
        btn_tenniscourt = new QPushButton(tab_venue);
        btn_tenniscourt->setObjectName(QString::fromUtf8("btn_tenniscourt"));
        btn_tenniscourt->setGeometry(QRect(98, 242, 91, 41));
        btn_tenniscourt->setCursor(QCursor(Qt::PointingHandCursor));
        btn_lectureroom = new QPushButton(tab_venue);
        btn_lectureroom->setObjectName(QString::fromUtf8("btn_lectureroom"));
        btn_lectureroom->setGeometry(QRect(1, 2, 91, 41));
        btn_lectureroom->setCursor(QCursor(Qt::PointingHandCursor));
        btn_gym = new QPushButton(tab_venue);
        btn_gym->setObjectName(QString::fromUtf8("btn_gym"));
        btn_gym->setGeometry(QRect(196, 302, 91, 41));
        btn_gym->setCursor(QCursor(Qt::PointingHandCursor));
        label_20 = new QLabel(tab_venue);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(3, 282, 47, 13));
        fac0007_lbl = new QLabel(tab_venue);
        fac0007_lbl->setObjectName(QString::fromUtf8("fac0007_lbl"));
        fac0007_lbl->setGeometry(QRect(346, 100, 41, 16));
        label_8 = new QLabel(tab_venue);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(3, 102, 47, 13));
        fac0006_lbl = new QLabel(tab_venue);
        fac0006_lbl->setObjectName(QString::fromUtf8("fac0006_lbl"));
        fac0006_lbl->setGeometry(QRect(248, 100, 41, 16));
        btn_greensroom = new QPushButton(tab_venue);
        btn_greensroom->setObjectName(QString::fromUtf8("btn_greensroom"));
        btn_greensroom->setGeometry(QRect(98, 122, 91, 41));
        btn_greensroom->setCursor(QCursor(Qt::PointingHandCursor));
        fac0008_lbl = new QLabel(tab_venue);
        fac0008_lbl->setObjectName(QString::fromUtf8("fac0008_lbl"));
        fac0008_lbl->setGeometry(QRect(53, 160, 41, 16));
        label_14 = new QLabel(tab_venue);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(3, 162, 47, 13));
        btn_tutorialroom = new QPushButton(tab_venue);
        btn_tutorialroom->setObjectName(QString::fromUtf8("btn_tutorialroom"));
        btn_tutorialroom->setGeometry(QRect(196, 2, 91, 41));
        btn_tutorialroom->setCursor(QCursor(Qt::PointingHandCursor));
        btn_eventhall = new QPushButton(tab_venue);
        btn_eventhall->setObjectName(QString::fromUtf8("btn_eventhall"));
        btn_eventhall->setGeometry(QRect(98, 182, 91, 41));
        btn_eventhall->setCursor(QCursor(Qt::PointingHandCursor));
        btn_basketballcourt = new QPushButton(tab_venue);
        btn_basketballcourt->setObjectName(QString::fromUtf8("btn_basketballcourt"));
        btn_basketballcourt->setGeometry(QRect(1, 242, 91, 41));
        btn_basketballcourt->setCursor(QCursor(Qt::PointingHandCursor));
        label_22 = new QLabel(tab_venue);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(100, 282, 47, 13));
        label_13 = new QLabel(tab_venue);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(296, 162, 47, 13));
        label_17 = new QLabel(tab_venue);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(3, 222, 47, 13));
        label_16 = new QLabel(tab_venue);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(100, 222, 47, 13));
        fac0003_lbl = new QLabel(tab_venue);
        fac0003_lbl->setObjectName(QString::fromUtf8("fac0003_lbl"));
        fac0003_lbl->setGeometry(QRect(344, 40, 41, 16));
        btn_explab = new QPushButton(tab_venue);
        btn_explab->setObjectName(QString::fromUtf8("btn_explab"));
        btn_explab->setGeometry(QRect(98, 62, 91, 41));
        btn_explab->setCursor(QCursor(Qt::PointingHandCursor));
        btn_engineerlab = new QPushButton(tab_venue);
        btn_engineerlab->setObjectName(QString::fromUtf8("btn_engineerlab"));
        btn_engineerlab->setGeometry(QRect(196, 62, 91, 41));
        btn_engineerlab->setCursor(QCursor(Qt::PointingHandCursor));
        label_7 = new QLabel(tab_venue);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(296, 42, 47, 13));
        fac0000_lbl = new QLabel(tab_venue);
        fac0000_lbl->setObjectName(QString::fromUtf8("fac0000_lbl"));
        fac0000_lbl->setGeometry(QRect(53, 40, 41, 16));
        btn_badmintoncourt = new QPushButton(tab_venue);
        btn_badmintoncourt->setObjectName(QString::fromUtf8("btn_badmintoncourt"));
        btn_badmintoncourt->setGeometry(QRect(196, 242, 91, 41));
        btn_badmintoncourt->setCursor(QCursor(Qt::PointingHandCursor));
        label_10 = new QLabel(tab_venue);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(198, 102, 47, 13));
        fac0022_lbl = new QLabel(tab_venue);
        fac0022_lbl->setObjectName(QString::fromUtf8("fac0022_lbl"));
        fac0022_lbl->setGeometry(QRect(248, 340, 41, 16));
        label_4 = new QLabel(tab_venue);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(3, 42, 47, 13));
        label_19 = new QLabel(tab_venue);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(296, 222, 47, 13));
        btn_meetingroom = new QPushButton(tab_venue);
        btn_meetingroom->setObjectName(QString::fromUtf8("btn_meetingroom"));
        btn_meetingroom->setGeometry(QRect(294, 62, 91, 41));
        btn_meetingroom->setCursor(QCursor(Qt::PointingHandCursor));
        label_9 = new QLabel(tab_venue);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(100, 102, 47, 13));
        btn_vidshootroom = new QPushButton(tab_venue);
        btn_vidshootroom->setObjectName(QString::fromUtf8("btn_vidshootroom"));
        btn_vidshootroom->setGeometry(QRect(196, 122, 91, 41));
        btn_vidshootroom->setCursor(QCursor(Qt::PointingHandCursor));
        fac0017_lbl = new QLabel(tab_venue);
        fac0017_lbl->setObjectName(QString::fromUtf8("fac0017_lbl"));
        fac0017_lbl->setGeometry(QRect(150, 280, 41, 16));
        btn_corridor = new QPushButton(tab_venue);
        btn_corridor->setObjectName(QString::fromUtf8("btn_corridor"));
        btn_corridor->setGeometry(QRect(196, 182, 91, 41));
        btn_corridor->setCursor(QCursor(Qt::PointingHandCursor));
        fac0020_lbl = new QLabel(tab_venue);
        fac0020_lbl->setObjectName(QString::fromUtf8("fac0020_lbl"));
        fac0020_lbl->setGeometry(QRect(53, 340, 41, 16));
        label_6 = new QLabel(tab_venue);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(196, 42, 47, 13));
        fac0023_lbl = new QLabel(tab_venue);
        fac0023_lbl->setObjectName(QString::fromUtf8("fac0023_lbl"));
        fac0023_lbl->setGeometry(QRect(344, 340, 41, 16));
        label_18 = new QLabel(tab_venue);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(198, 222, 47, 13));
        label_23 = new QLabel(tab_venue);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(294, 282, 47, 13));
        tabWidget->addTab(tab_venue, QString());
        tab_fac = new QWidget();
        tab_fac->setObjectName(QString::fromUtf8("tab_fac"));
        label_30 = new QLabel(tab_fac);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(195, 40, 47, 13));
        fac0025_lbl = new QLabel(tab_fac);
        fac0025_lbl->setObjectName(QString::fromUtf8("fac0025_lbl"));
        fac0025_lbl->setGeometry(QRect(151, 38, 41, 16));
        fac0030_lbl = new QLabel(tab_fac);
        fac0030_lbl->setObjectName(QString::fromUtf8("fac0030_lbl"));
        fac0030_lbl->setGeometry(QRect(245, 98, 41, 16));
        btn_bannerstand = new QPushButton(tab_fac);
        btn_bannerstand->setObjectName(QString::fromUtf8("btn_bannerstand"));
        btn_bannerstand->setGeometry(QRect(193, 60, 91, 41));
        btn_bannerstand->setCursor(QCursor(Qt::PointingHandCursor));
        label_33 = new QLabel(tab_fac);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(290, 100, 47, 13));
        btn_waterwiper = new QPushButton(tab_fac);
        btn_waterwiper->setObjectName(QString::fromUtf8("btn_waterwiper"));
        btn_waterwiper->setGeometry(QRect(193, 120, 91, 41));
        btn_waterwiper->setCursor(QCursor(Qt::PointingHandCursor));
        fac0029_lbl = new QLabel(tab_fac);
        fac0029_lbl->setObjectName(QString::fromUtf8("fac0029_lbl"));
        fac0029_lbl->setGeometry(QRect(151, 98, 41, 16));
        btn_chair = new QPushButton(tab_fac);
        btn_chair->setObjectName(QString::fromUtf8("btn_chair"));
        btn_chair->setGeometry(QRect(288, 0, 91, 41));
        btn_chair->setCursor(QCursor(Qt::PointingHandCursor));
        btn_ladder = new QPushButton(tab_fac);
        btn_ladder->setObjectName(QString::fromUtf8("btn_ladder"));
        btn_ladder->setGeometry(QRect(4, 60, 91, 41));
        btn_ladder->setCursor(QCursor(Qt::PointingHandCursor));
        fac0027_lbl = new QLabel(tab_fac);
        fac0027_lbl->setObjectName(QString::fromUtf8("fac0027_lbl"));
        fac0027_lbl->setGeometry(QRect(340, 38, 41, 16));
        label_28 = new QLabel(tab_fac);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(101, 40, 47, 13));
        fac0024_lbl = new QLabel(tab_fac);
        fac0024_lbl->setObjectName(QString::fromUtf8("fac0024_lbl"));
        fac0024_lbl->setGeometry(QRect(57, 38, 41, 16));
        btn_waterbucket = new QPushButton(tab_fac);
        btn_waterbucket->setObjectName(QString::fromUtf8("btn_waterbucket"));
        btn_waterbucket->setGeometry(QRect(4, 120, 91, 41));
        btn_waterbucket->setCursor(QCursor(Qt::PointingHandCursor));
        label_29 = new QLabel(tab_fac);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(7, 40, 47, 13));
        fac0026_lbl = new QLabel(tab_fac);
        fac0026_lbl->setObjectName(QString::fromUtf8("fac0026_lbl"));
        fac0026_lbl->setGeometry(QRect(245, 38, 41, 16));
        label_36 = new QLabel(tab_fac);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(195, 160, 47, 13));
        btn_broom = new QPushButton(tab_fac);
        btn_broom->setObjectName(QString::fromUtf8("btn_broom"));
        btn_broom->setGeometry(QRect(5, 0, 91, 41));
        btn_broom->setCursor(QCursor(Qt::PointingHandCursor));
        fac0028_lbl = new QLabel(tab_fac);
        fac0028_lbl->setObjectName(QString::fromUtf8("fac0028_lbl"));
        fac0028_lbl->setGeometry(QRect(57, 98, 41, 16));
        label_37 = new QLabel(tab_fac);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(101, 160, 47, 13));
        fac0033_lbl = new QLabel(tab_fac);
        fac0033_lbl->setObjectName(QString::fromUtf8("fac0033_lbl"));
        fac0033_lbl->setGeometry(QRect(151, 158, 41, 16));
        label_38 = new QLabel(tab_fac);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(7, 160, 47, 13));
        fac0031_lbl = new QLabel(tab_fac);
        fac0031_lbl->setObjectName(QString::fromUtf8("fac0031_lbl"));
        fac0031_lbl->setGeometry(QRect(340, 98, 41, 16));
        btn_waterpipe = new QPushButton(tab_fac);
        btn_waterpipe->setObjectName(QString::fromUtf8("btn_waterpipe"));
        btn_waterpipe->setGeometry(QRect(99, 120, 91, 41));
        btn_waterpipe->setCursor(QCursor(Qt::PointingHandCursor));
        fac0032_lbl = new QLabel(tab_fac);
        fac0032_lbl->setObjectName(QString::fromUtf8("fac0032_lbl"));
        fac0032_lbl->setGeometry(QRect(57, 158, 41, 16));
        fac0034_lbl = new QLabel(tab_fac);
        fac0034_lbl->setObjectName(QString::fromUtf8("fac0034_lbl"));
        fac0034_lbl->setGeometry(QRect(245, 158, 41, 16));
        label_34 = new QLabel(tab_fac);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(7, 100, 47, 13));
        btn_queuebarrier = new QPushButton(tab_fac);
        btn_queuebarrier->setObjectName(QString::fromUtf8("btn_queuebarrier"));
        btn_queuebarrier->setGeometry(QRect(99, 60, 91, 41));
        btn_queuebarrier->setCursor(QCursor(Qt::PointingHandCursor));
        label_35 = new QLabel(tab_fac);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(195, 100, 47, 13));
        label_32 = new QLabel(tab_fac);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(101, 100, 47, 13));
        btn_mop = new QPushButton(tab_fac);
        btn_mop->setObjectName(QString::fromUtf8("btn_mop"));
        btn_mop->setGeometry(QRect(99, 0, 91, 41));
        btn_mop->setCursor(QCursor(Qt::PointingHandCursor));
        btn_table = new QPushButton(tab_fac);
        btn_table->setObjectName(QString::fromUtf8("btn_table"));
        btn_table->setGeometry(QRect(193, 0, 91, 41));
        btn_table->setCursor(QCursor(Qt::PointingHandCursor));
        btn_bucket = new QPushButton(tab_fac);
        btn_bucket->setObjectName(QString::fromUtf8("btn_bucket"));
        btn_bucket->setGeometry(QRect(288, 60, 91, 41));
        btn_bucket->setCursor(QCursor(Qt::PointingHandCursor));
        label_31 = new QLabel(tab_fac);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(290, 40, 47, 13));
        tabWidget->addTab(tab_fac, QString());
        datedisplay = new QLabel(frameuser);
        datedisplay->setObjectName(QString::fromUtf8("datedisplay"));
        datedisplay->setGeometry(QRect(303, 2, 71, 16));
        timecmbBox = new QComboBox(frameuser);
        timecmbBox->addItem(QString());
        timecmbBox->addItem(QString());
        timecmbBox->addItem(QString());
        timecmbBox->addItem(QString());
        timecmbBox->addItem(QString());
        timecmbBox->setObjectName(QString::fromUtf8("timecmbBox"));
        timecmbBox->setGeometry(QRect(85, 270, 281, 21));
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(10, 30, 781, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        oframe1 = new QFrame(centralwidget);
        oframe1->setObjectName(QString::fromUtf8("oframe1"));
        oframe1->setGeometry(QRect(0, 10, 20, 581));
        oframe1->setFrameShape(QFrame::VLine);
        oframe1->setFrameShadow(QFrame::Sunken);
        oframe4 = new QFrame(centralwidget);
        oframe4->setObjectName(QString::fromUtf8("oframe4"));
        oframe4->setGeometry(QRect(10, 580, 781, 20));
        oframe4->setFrameShape(QFrame::HLine);
        oframe4->setFrameShadow(QFrame::Sunken);
        oframe3 = new QFrame(centralwidget);
        oframe3->setObjectName(QString::fromUtf8("oframe3"));
        oframe3->setGeometry(QRect(780, 10, 20, 581));
        oframe3->setFrameShape(QFrame::VLine);
        oframe3->setFrameShadow(QFrame::Sunken);
        oframe2 = new QFrame(centralwidget);
        oframe2->setObjectName(QString::fromUtf8("oframe2"));
        oframe2->setGeometry(QRect(10, 0, 781, 16));
        oframe2->setFrameShape(QFrame::HLine);
        oframe2->setFrameShadow(QFrame::Sunken);
        frameadmin = new QFrame(centralwidget);
        frameadmin->setObjectName(QString::fromUtf8("frameadmin"));
        frameadmin->setGeometry(QRect(5, 45, 781, 581));
        frameadmin->setFrameShape(QFrame::StyledPanel);
        frameadmin->setFrameShadow(QFrame::Raised);
        datedisplay_2 = new QLabel(frameadmin);
        datedisplay_2->setObjectName(QString::fromUtf8("datedisplay_2"));
        datedisplay_2->setGeometry(QRect(700, 2, 71, 16));
        datedisplaylbl2 = new QLabel(frameadmin);
        datedisplaylbl2->setObjectName(QString::fromUtf8("datedisplaylbl2"));
        datedisplaylbl2->setGeometry(QRect(627, 2, 71, 16));
        table_availability = new QTableView(frameadmin);
        table_availability->setObjectName(QString::fromUtf8("table_availability"));
        table_availability->setGeometry(QRect(10, 25, 771, 491));
        table_availability->horizontalHeader()->setCascadingSectionResizes(true);
        table_availability->horizontalHeader()->setMinimumSectionSize(150);
        table_availability->horizontalHeader()->setDefaultSectionSize(150);
        table_availability->horizontalHeader()->setStretchLastSection(true);
        frameadmin2 = new QFrame(centralwidget);
        frameadmin2->setObjectName(QString::fromUtf8("frameadmin2"));
        frameadmin2->setGeometry(QRect(10, 40, 791, 561));
        frameadmin2->setFrameShape(QFrame::StyledPanel);
        frameadmin2->setFrameShadow(QFrame::Raised);
        table_bookings = new QTableView(frameadmin2);
        table_bookings->setObjectName(QString::fromUtf8("table_bookings"));
        table_bookings->setGeometry(QRect(5, 30, 771, 491));
        table_bookings->horizontalHeader()->setCascadingSectionResizes(true);
        table_bookings->horizontalHeader()->setMinimumSectionSize(94);
        table_bookings->horizontalHeader()->setDefaultSectionSize(94);
        table_bookings->horizontalHeader()->setStretchLastSection(true);
        table_bookings->verticalHeader()->setCascadingSectionResizes(false);
        table_bookings->verticalHeader()->setStretchLastSection(false);
        datedisplaylbl2_2 = new QLabel(frameadmin2);
        datedisplaylbl2_2->setObjectName(QString::fromUtf8("datedisplaylbl2_2"));
        datedisplaylbl2_2->setGeometry(QRect(622, 7, 71, 16));
        datedisplay_3 = new QLabel(frameadmin2);
        datedisplay_3->setObjectName(QString::fromUtf8("datedisplay_3"));
        datedisplay_3->setGeometry(QRect(695, 7, 71, 16));
        timecurrentLabel = new QLabel(centralwidget);
        timecurrentLabel->setObjectName(QString::fromUtf8("timecurrentLabel"));
        timecurrentLabel->setGeometry(QRect(17, 45, 101, 16));
        timedisplay = new QLabel(centralwidget);
        timedisplay->setObjectName(QString::fromUtf8("timedisplay"));
        timedisplay->setGeometry(QRect(100, 46, 111, 16));
        Booking->setCentralWidget(centralwidget);
        userLabel->raise();
        btn_logout->raise();
        currentuser_lbl->raise();
        copyright->raise();
        db_lbl->raise();
        btn_return->raise();
        line_2->raise();
        oframe1->raise();
        oframe4->raise();
        oframe3->raise();
        oframe2->raise();
        frameadmin2->raise();
        timecurrentLabel->raise();
        timedisplay->raise();
        frameadmin->raise();
        frameuser->raise();

        retranslateUi(Booking);

        btn_logout->setDefault(false);
        btn_return->setDefault(false);
        btn_confirm->setDefault(false);
        btn_reset->setDefault(false);
        btn_reset_2->setDefault(false);
        btn_reset_3->setDefault(false);
        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Booking);
    } // setupUi

    void retranslateUi(QMainWindow *Booking)
    {
        Booking->setWindowTitle(QCoreApplication::translate("Booking", "University Faclilities Management System (UFMS)", nullptr));
        userLabel->setText(QCoreApplication::translate("Booking", "Current Session:", nullptr));
        btn_logout->setText(QCoreApplication::translate("Booking", "LOGOUT", nullptr));
        currentuser_lbl->setText(QCoreApplication::translate("Booking", "USERNAME", nullptr));
        copyright->setText(QCoreApplication::translate("Booking", "\302\251 SLAUATRON 2019.", nullptr));
        db_lbl->setText(QString());
        btn_return->setText(QCoreApplication::translate("Booking", "RETURN", nullptr));
        groupBox->setTitle(QString());
        time1hourbox->setTitle(QCoreApplication::translate("Booking", "Booking Time", nullptr));
        btn_8am->setText(QCoreApplication::translate("Booking", "0800 ~ 0900", nullptr));
        btn_9am->setText(QCoreApplication::translate("Booking", "0900 ~ 1000", nullptr));
        btn_10am->setText(QCoreApplication::translate("Booking", "1000 ~ 1100", nullptr));
        btn_11am->setText(QCoreApplication::translate("Booking", "1100 ~ 1200", nullptr));
        btn_12pm->setText(QCoreApplication::translate("Booking", "1200 ~ 1300", nullptr));
        btn_1pm->setText(QCoreApplication::translate("Booking", "1300 ~ 1400", nullptr));
        btn_2pm->setText(QCoreApplication::translate("Booking", "1400 ~ 1500", nullptr));
        btn_3pm->setText(QCoreApplication::translate("Booking", "1500 ~ 1600", nullptr));
        btn_4pm->setText(QCoreApplication::translate("Booking", "1600 ~ 1700", nullptr));
        btn_5pm->setText(QCoreApplication::translate("Booking", "1700 ~ 1800", nullptr));
        btn_6pm->setText(QCoreApplication::translate("Booking", "1800 ~ 1900", nullptr));
        btn_7pm->setText(QCoreApplication::translate("Booking", "1900 ~ 2000", nullptr));
        btn_8pm->setText(QCoreApplication::translate("Booking", "2000 ~ 2100", nullptr));
        btn_9pm->setText(QCoreApplication::translate("Booking", "2100 ~ 2200", nullptr));
        btn_wholeday->setText(QCoreApplication::translate("Booking", "Book for WHOLE DAY", nullptr));
#if QT_CONFIG(tooltip)
        calendarWidget->setToolTip(QString());
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        calendarWidget->setWhatsThis(QString());
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        calendarWidget->setAccessibleName(QString());
#endif // QT_CONFIG(accessibility)
        time2hourbox->setTitle(QCoreApplication::translate("Booking", "Booking Time", nullptr));
        btn_8am_2->setText(QCoreApplication::translate("Booking", "0800 ~ 1000", nullptr));
        btn_10am_2->setText(QCoreApplication::translate("Booking", "1000 ~ 1200", nullptr));
        btn_12pm_2->setText(QCoreApplication::translate("Booking", "1200 ~ 1400", nullptr));
        btn_2pm_2->setText(QCoreApplication::translate("Booking", "1400 ~ 1600", nullptr));
        btn_4pm_2->setText(QCoreApplication::translate("Booking", "1600 ~ 1800", nullptr));
        btn_6pm_2->setText(QCoreApplication::translate("Booking", "1800 ~ 2000", nullptr));
        btn_8pm_2->setText(QCoreApplication::translate("Booking", "2000 ~ 2200", nullptr));
        btn_wholeday_2->setText(QCoreApplication::translate("Booking", "Book for WHOLE DAY", nullptr));
        time3hourbox->setTitle(QCoreApplication::translate("Booking", "Booking Time", nullptr));
        btn_8am_3->setText(QCoreApplication::translate("Booking", "0800 ~ 1100", nullptr));
        btn_11am_3->setText(QCoreApplication::translate("Booking", "1100 ~ 1400", nullptr));
        btn_2pm_3->setText(QCoreApplication::translate("Booking", "1400 ~ 1700", nullptr));
        btn_5pm_3->setText(QCoreApplication::translate("Booking", "1700 ~ 2000", nullptr));
        btn_8pm_3->setText(QCoreApplication::translate("Booking", "2000 ~ 2200", nullptr));
        btn_wholeday_3->setText(QCoreApplication::translate("Booking", "Book for WHOLE DAY", nullptr));
        time4hourbox->setTitle(QCoreApplication::translate("Booking", "Booking Time", nullptr));
        btn_8am_4->setText(QCoreApplication::translate("Booking", "0800 ~ 1200", nullptr));
        btn_12pm_4->setText(QCoreApplication::translate("Booking", "1200 ~ 1600", nullptr));
        btn_4pm_4->setText(QCoreApplication::translate("Booking", "1600 ~ 2000", nullptr));
        btn_wholeday_4->setText(QCoreApplication::translate("Booking", "Book for WHOLE DAY", nullptr));
        timecustomize->setTitle(QCoreApplication::translate("Booking", "Booking Time", nullptr));
        label->setText(QCoreApplication::translate("Booking", "Preferred Time :", nullptr));
        timefromcmbbox->setItemText(0, QCoreApplication::translate("Booking", "0800", nullptr));
        timefromcmbbox->setItemText(1, QCoreApplication::translate("Booking", "0900", nullptr));
        timefromcmbbox->setItemText(2, QCoreApplication::translate("Booking", "1000", nullptr));
        timefromcmbbox->setItemText(3, QCoreApplication::translate("Booking", "1100", nullptr));
        timefromcmbbox->setItemText(4, QCoreApplication::translate("Booking", "1200", nullptr));
        timefromcmbbox->setItemText(5, QCoreApplication::translate("Booking", "1300", nullptr));
        timefromcmbbox->setItemText(6, QCoreApplication::translate("Booking", "1400", nullptr));
        timefromcmbbox->setItemText(7, QCoreApplication::translate("Booking", "1500", nullptr));
        timefromcmbbox->setItemText(8, QCoreApplication::translate("Booking", "1600", nullptr));
        timefromcmbbox->setItemText(9, QCoreApplication::translate("Booking", "1700", nullptr));
        timefromcmbbox->setItemText(10, QCoreApplication::translate("Booking", "1800", nullptr));
        timefromcmbbox->setItemText(11, QCoreApplication::translate("Booking", "1900", nullptr));
        timefromcmbbox->setItemText(12, QCoreApplication::translate("Booking", "2000", nullptr));
        timefromcmbbox->setItemText(13, QCoreApplication::translate("Booking", "2100", nullptr));

        label_2->setText(QCoreApplication::translate("Booking", "~", nullptr));
        label_3->setText(QCoreApplication::translate("Booking", "*Date Range    :", nullptr));
        label_39->setText(QCoreApplication::translate("Booking", "*Field is optional.", nullptr));
        dateEditfrom->setDisplayFormat(QCoreApplication::translate("Booking", "yyyy-MM-dd", nullptr));
        label_40->setText(QCoreApplication::translate("Booking", "*Preferred Day:", nullptr));
        dateEditto->setDisplayFormat(QCoreApplication::translate("Booking", "yyyy-MM-dd", nullptr));
        label_41->setText(QCoreApplication::translate("Booking", "~", nullptr));
        daycmbbox->setItemText(0, QString());
        daycmbbox->setItemText(1, QCoreApplication::translate("Booking", "Sunday", nullptr));
        daycmbbox->setItemText(2, QCoreApplication::translate("Booking", "Monday", nullptr));
        daycmbbox->setItemText(3, QCoreApplication::translate("Booking", "Tuesday", nullptr));
        daycmbbox->setItemText(4, QCoreApplication::translate("Booking", "Wednesday", nullptr));
        daycmbbox->setItemText(5, QCoreApplication::translate("Booking", "Thursday", nullptr));
        daycmbbox->setItemText(6, QCoreApplication::translate("Booking", "Friday", nullptr));
        daycmbbox->setItemText(7, QCoreApplication::translate("Booking", "Saturday", nullptr));

        btn_customconfirm->setText(QCoreApplication::translate("Booking", "CONFIRM", nullptr));
        btn_customreset->setText(QCoreApplication::translate("Booking", "RESET", nullptr));
        pushbtn_->setText(QCoreApplication::translate("Booking", "Today's Date", nullptr));
        confirmation->setTitle(QString());
        facselected_lbl->setText(QCoreApplication::translate("Booking", "-", nullptr));
        maxfac_lbl->setText(QCoreApplication::translate("Booking", "-", nullptr));
        btn_confirm->setText(QCoreApplication::translate("Booking", "CONFIRM", nullptr));
        selecteddis_lbl_2->setText(QCoreApplication::translate("Booking", "Max Amount for Booking:", nullptr));
        selecteddis_lbl_3->setText(QCoreApplication::translate("Booking", "Amount Needed             : ", nullptr));
        selecteddis_lbl->setText(QCoreApplication::translate("Booking", "Selected Venue/Facilities:", nullptr));
        btn_reset->setText(QCoreApplication::translate("Booking", "RESET ALL", nullptr));
        dateselectLabel->setText(QCoreApplication::translate("Booking", "Selected Date:", nullptr));
        timeselectedLabel->setText(QCoreApplication::translate("Booking", "-", nullptr));
        dateselectedLabel->setText(QCoreApplication::translate("Booking", "-", nullptr));
        timeselectLabel->setText(QCoreApplication::translate("Booking", "Selected Time:", nullptr));
        btn_reset_2->setText(QCoreApplication::translate("Booking", "RESET Date and Time", nullptr));
        btn_reset_3->setText(QCoreApplication::translate("Booking", "RESET Venue/Facilities", nullptr));
        dayselectLabel->setText(QCoreApplication::translate("Booking", "Preferred Day:", nullptr));
        dayselectedLabel->setText(QCoreApplication::translate("Booking", "-", nullptr));
        btn_artroom->setText(QCoreApplication::translate("Booking", "Art Room", nullptr));
        fac0004_lbl->setText(QString());
        fac0013_lbl->setText(QString());
        fac0005_lbl->setText(QString());
        fac0021_lbl->setText(QString());
        btn_audioroom->setText(QCoreApplication::translate("Booking", "Acoustic Audio\n"
" Record Room", nullptr));
        fac0015_lbl->setText(QString());
        fac0018_lbl->setText(QString());
        fac0014_lbl->setText(QString());
        label_25->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_11->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_lecturehall->setText(QCoreApplication::translate("Booking", "Lecture Hall", nullptr));
        fac0016_lbl->setText(QString());
        fac0001_lbl->setText(QString());
        btn_videoeditroom->setText(QCoreApplication::translate("Booking", "Video Editing\n"
" Room", nullptr));
        fac0009_lbl->setText(QString());
        label_24->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0012_lbl->setText(QString());
        label_5->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0011_lbl->setText(QString());
        btn_volleycourt->setText(QCoreApplication::translate("Booking", "Volleyball Court", nullptr));
        label_21->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_pclab->setText(QCoreApplication::translate("Booking", "PC Laboratory", nullptr));
        label_26->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0010_lbl->setText(QString());
        label_12->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0019_lbl->setText(QString());
        fac0002_lbl->setText(QString());
        btn_field->setText(QCoreApplication::translate("Booking", "Field", nullptr));
        btn_pool->setText(QCoreApplication::translate("Booking", "Swimming Pool", nullptr));
        btn_oslab->setText(QCoreApplication::translate("Booking", "OS Laboratory", nullptr));
        btn_plaza->setText(QCoreApplication::translate("Booking", "Plaza", nullptr));
        label_27->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_15->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_skatepark->setText(QCoreApplication::translate("Booking", "Skatepark", nullptr));
        btn_tenniscourt->setText(QCoreApplication::translate("Booking", "Tennis Court", nullptr));
        btn_lectureroom->setText(QCoreApplication::translate("Booking", "Lecture Room", nullptr));
        btn_gym->setText(QCoreApplication::translate("Booking", "Gym", nullptr));
        label_20->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0007_lbl->setText(QString());
        label_8->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0006_lbl->setText(QString());
        btn_greensroom->setText(QCoreApplication::translate("Booking", "Green Screen\n"
" Room", nullptr));
        fac0008_lbl->setText(QString());
        label_14->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_tutorialroom->setText(QCoreApplication::translate("Booking", "Tutorial Room", nullptr));
        btn_eventhall->setText(QCoreApplication::translate("Booking", "Event Hall", nullptr));
        btn_basketballcourt->setText(QCoreApplication::translate("Booking", "Basketball Court", nullptr));
        label_22->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_13->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_17->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_16->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0003_lbl->setText(QString());
        btn_explab->setText(QCoreApplication::translate("Booking", "Experimental \n"
"Laboratory", nullptr));
        btn_engineerlab->setText(QCoreApplication::translate("Booking", "Engineering \n"
"Laboratory", nullptr));
        label_7->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0000_lbl->setText(QString());
        btn_badmintoncourt->setText(QCoreApplication::translate("Booking", "Badminton Court", nullptr));
        label_10->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0022_lbl->setText(QString());
        label_4->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_19->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_meetingroom->setText(QCoreApplication::translate("Booking", "Meeting Room", nullptr));
        label_9->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_vidshootroom->setText(QCoreApplication::translate("Booking", "Video Shooting\n"
" Room", nullptr));
        fac0017_lbl->setText(QString());
        btn_corridor->setText(QCoreApplication::translate("Booking", "Corridor", nullptr));
        fac0020_lbl->setText(QString());
        label_6->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0023_lbl->setText(QString());
        label_18->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_23->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_venue), QCoreApplication::translate("Booking", "Venue", nullptr));
        label_30->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0025_lbl->setText(QString());
        fac0030_lbl->setText(QString());
        btn_bannerstand->setText(QCoreApplication::translate("Booking", "Banner Stand", nullptr));
        label_33->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_waterwiper->setText(QCoreApplication::translate("Booking", "Water Wiper", nullptr));
        fac0029_lbl->setText(QString());
        btn_chair->setText(QCoreApplication::translate("Booking", "Chair", nullptr));
        btn_ladder->setText(QCoreApplication::translate("Booking", "Ladder", nullptr));
        fac0027_lbl->setText(QString());
        label_28->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0024_lbl->setText(QString());
        btn_waterbucket->setText(QCoreApplication::translate("Booking", "Water Bucket", nullptr));
        label_29->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0026_lbl->setText(QString());
        label_36->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_broom->setText(QCoreApplication::translate("Booking", "Broom", nullptr));
        fac0028_lbl->setText(QString());
        label_37->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0033_lbl->setText(QString());
        label_38->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        fac0031_lbl->setText(QString());
        btn_waterpipe->setText(QCoreApplication::translate("Booking", "Water Pipe", nullptr));
        fac0032_lbl->setText(QString());
        fac0034_lbl->setText(QString());
        label_34->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_queuebarrier->setText(QCoreApplication::translate("Booking", "Queue Barrier", nullptr));
        label_35->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        label_32->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        btn_mop->setText(QCoreApplication::translate("Booking", "Mop", nullptr));
        btn_table->setText(QCoreApplication::translate("Booking", "Table", nullptr));
        btn_bucket->setText(QCoreApplication::translate("Booking", "Bucket", nullptr));
        label_31->setText(QCoreApplication::translate("Booking", "Available: ", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_fac), QCoreApplication::translate("Booking", "Facilities", nullptr));
        datedisplay->setText(QCoreApplication::translate("Booking", ":  DATE", nullptr));
        timecmbBox->setItemText(0, QCoreApplication::translate("Booking", "1 Hour(s)", nullptr));
        timecmbBox->setItemText(1, QCoreApplication::translate("Booking", "2 Hour(s)", nullptr));
        timecmbBox->setItemText(2, QCoreApplication::translate("Booking", "3 Hour(s)", nullptr));
        timecmbBox->setItemText(3, QCoreApplication::translate("Booking", "4 Hour(s)", nullptr));
        timecmbBox->setItemText(4, QCoreApplication::translate("Booking", "Customize", nullptr));

        datedisplay_2->setText(QCoreApplication::translate("Booking", "date", nullptr));
        datedisplaylbl2->setText(QCoreApplication::translate("Booking", "Today's Date:", nullptr));
        datedisplaylbl2_2->setText(QCoreApplication::translate("Booking", "Today's Date:", nullptr));
        datedisplay_3->setText(QCoreApplication::translate("Booking", "date", nullptr));
        timecurrentLabel->setText(QCoreApplication::translate("Booking", "Current Time   :", nullptr));
        timedisplay->setText(QCoreApplication::translate("Booking", "CLOCK", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Booking: public Ui_Booking {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BOOKING_H
